version: '3.8'


services:
  db:
    image: mysql:8.0.35
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: blog
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}

    ports:
      - "3306:3306"

    volumes:
      - db_data:/var/lib/mysql


volumes:
  db_data:
