version: '3.8'


services:
  db:
    image: mysql:8.0.35
    environment:
      MYSQL_ROOT_PASSWORD: lucaspdev
      MYSQL_DATABASE: blog
      MYSQL_USER: devlucasp
      MYSQL_PASSWORD: lucaspdev

    ports:
      - "3306:3306"

    volumes:
      - db_data:/var/lib/mysql


volumes:
  db_data:
